americana/urls.py
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.urls import path

from americana import views

app_name = 'repo-ame'

urlpatterns = [
    path('', views.index, name='home'),
    path('search', views.search, name='search'),
    path('tablero/', views.Tablero.as_view(), name='tablero'),

    # Tesis
    path('tesis/', views.TesisListView.as_view(), name='tesis'),
    path('tesis/<int:pk>/update', views.TesisUpdateView.as_view(), name='tesis-update'),
    path('tesis/<int:pk>/delete', views.TesisDeleteView.as_view(), name='tesis-delete'),
    path('tesis/modal/<int:pk>/', views.tesis_modal_summary, name='tesis-modal-summary'),

    # Publicaciones
    path('publicaciones/', views.PublicacionListView.as_view(), name='publicacion'),
    path('publicacion/<int:pk>/update', views.PublicacionUpdateView.as_view(), name='publicacion-update'),
    path('publicacion/<int:pk>/delete', views.PublicacionDeleteView.as_view(), name='publicacion-delete'),
    path('publicaciones/modal/<int:pk>/', views.publicacion_modal_summary, name='publicacion-modal-summary'),

    # path('signup/', views.signup, name='signup'),
    # path('profile/update/', views.update_profile, name='profile-update'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout')
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

repos/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('americana.urls', namespace='repo-ame')),
]

admin.site.site_header = 'Universidad Americana de Acapulco'
admin.site.site_title = 'Portal de Administración'
admin.site.index_title = 'Sitio de Administración del Repositorio'

templates/americana/publicacion/partials/modal.html
<div class="modal" _="on click transition opacity to 0 then remove me">
<div class="modal-background"></div>
<div class="modal-card">
    <header class="modal-card-head">
    <p class="modal-card-title"></p>
    <button class="delete" aria-label="close"></button>
    </header>
    <section class="modal-card-body">
    <p class="title is-5 has-text-justified">{{publicacion.title}}</p>
    <p class="has-text-justified">{{publicacion.description}}</p>
    </section>
    <footer class="modal-card-foot">
    </footer>
</div>
</div>

templates/americana/publicacion/partials/table-dashboard.html
<div class="table-container mt-4">
<table class="table is-striped is-fullwidth">
<thead class="has-background-light">
<tr>
    <th>Fecha de Publicación</th>
    <th>Publicado en</th>
    <th>Titulo</th>
    <th>Resumen</th>
    <th>Articulo</th>
    <th>Código de Publicación</th>
    <th>Acciones</th>
</tr>
</thead>
<tbody>
{% for p in publicaciones  %}
<tr>
    <td>{{p.publish_date}}</td>
    <td>{{p.conference}}</td>
    <td>{{p.title}}</td>
    <td>
        <button class="button is-link" 
            hx-get="{% url 'repo-ame:publicacion-modal-summary' p.id %}"
            hx-target="#modal-summary"
            _="on every htmx:afterOnLoad add .is-active to .modal"
        >
            <span class="icon">
                <i class="far fa-file-alt"></i>
            </span>
            <span>Ver más</span>
            </button>
    </td>
    <td>
        <span class="icon is-large">
            <a href="{{p.file.url}}" target="_blank">
                <i class="fas fa-2x fa-file-pdf"></i>
            </a>
        </span>
    </td>
    <td>
        <p class="is-family-code">{{p.issn}}</p>
        <p class="is-family-code">{{p.isbn}}</p>
    </td>
    <td>
        <div class="field is-grouped">
            <p class="control">
                <div class="icon-text">
                    <a href="{% url 'repo-ame:publicacion-update' p.pk %}">
                    <span class="icon has-text-info">
                        <i class="fas fa-edit"></i>
                    </span>
                    </a>
                </div>
            </p>
            <p class="control">
                <div class="icon-text">
                    <a href="{% url 'repo-ame:publicacion-delete' p.pk %}">
                    <span class="icon has-text-danger">
                        <i class="fas fa-trash"></i>
                    </span>
                    </a>
                </div>
            </p>
        </div>
    </td>
</tr>
{% endfor %}
</tbody>
</table>
</div>
{% if publicaciones %}
<nav class="pagination is-right" role="navigation" aria-label="pagination" hx-target="#results-publicacion" hx-push-url="true">
    {% if publicaciones.has_previous %}  
    <a hx-get="?page={{ publicaciones.previous_page_number }}&model=publicacion" href="?page={{ publicaciones.previous_page_number }}&model=publicacion" class="pagination-previous button is-link is-outlined">Atrás</a>
    {% endif %}
    {% if publicaciones.has_next %}
    <a hx-get="?page={{ publicaciones.next_page_number }}&model=publicacion" href="?page={{ publicaciones.next_page_number }}&model=publicacion" class="pagination-next button is-link is-outlined">Siguiente</a>
    {% endif %}
    <ul class="pagination-list">
    {% for number in publicaciones.paginator.page_range %}
        {% ifequal number publicaciones.number %}
        <li>
            <a hx-get="?page={{number}}&model=publicacion" href="?page={{number}}&model=publicacion" class="pagination-link is-current" aria-label="Ir a página {{number}}">{{number}}</a>
        </li>
        {% else %}
        <li>
            <a hx-get="?page={{number}}&model=publicacion" href="?page={{number}}&model=publicacion" class="pagination-link" aria-label="Ir a página {{number}}">{{number}}</a>
        </li>
        {% endifequal %}
    {% endfor %}
    </ul>
</nav>
{% endif %}

templates/americana/publicacion/partials/table.html
<div class="table-container mt-6">
<table class="table is-striped is-fullwidth">
<thead class="has-background-light">
    <tr>
        <th>Fecha de Publicación</th>
        <th>Publicado en</th>
        <th>Titulo</th>
        <th>Resumen</th>
        <th>Articulo</th>
        <th>Fecha de Creación</th>
    </tr>
</thead>
<tbody class="has-background-light">
    {% for p in publicaciones  %}
    <tr>
        <td>{{p.publish_date}}</td>
        <td>{{p.conference}}</td>
        <td>{{p.title}}</td>
        <td>
            <button class="button is-link" 
                hx-get="{% url 'repo-ame:publicacion-modal-summary' p.id %}"
                hx-target="#modal-summary"
                _="on every htmx:afterOnLoad add .is-active to .modal"
            >
                <span class="icon">
                    <i class="far fa-file-alt"></i>
                </span>
                <span>Ver más</span>
                </button>
        </td>
        <td>
            <span class="icon is-large">
                <a href="{{p.file.url}}" target="_blank">
                    <i class="fas fa-2x fa-file-pdf"></i>
                </a>
            </span>
        </td>
        <td>{{p.created_at}}</td>
    </tr>
    {% endfor %}
</tbody>
</table>
</div>
{% if publicaciones %}
<nav class="pagination is-right" role="navigation" aria-label="pagination" hx-target="#results" hx-push-url="true">
    {% if publicaciones.has_previous %}  
    <a hx-get="?page={{ publicaciones.previous_page_number }}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}" href="?page={{ publicaciones.previous_page_number }}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}" class="pagination-previous button is-link is-outlined">Atrás</a>
    {% endif %}
    {% if publicaciones.has_next %}
    <a hx-get="?page={{ publicaciones.next_page_number }}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}" href="?page={{ publicaciones.next_page_number }}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}" class="pagination-next button is-link is-outlined">Siguiente</a>
    {% endif %}
    <ul class="pagination-list">
    {% for number in publicaciones.paginator.page_range %}
        {% ifequal number publicaciones.number %}
        <li>
            <a hx-get="?page={{number}}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}" href="?page={{number}}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}" class="pagination-link is-current" aria-label="Ir a página {{number}}">{{number}}</a>
        </li>
        {% else %}
        <li>
            <a hx-get="?page={{number}}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}" href="?page={{number}}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}" class="pagination-link" aria-label="Ir a página {{number}}">{{number}}</a>
        </li>
        {% endifequal %}
    {% endfor %}
    </ul>
</nav>
{% endif %}