americana/urls.py
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.urls import path

from americana import views

app_name = 'repo-ame'

urlpatterns = [
    path('', views.index, name='home'),
    path('search', views.search, name='search'),
    path('tablero/', views.Tablero.as_view(), name='tablero'),

    # Tesis
    path('tesis/', views.TesisListView.as_view(), name='tesis'),
    path('tesis/<int:pk>/update', views.TesisUpdateView.as_view(), name='tesis-update'),
    path('tesis/<int:pk>/delete', views.TesisDeleteView.as_view(), name='tesis-delete'),
    path('tesis/modal/<int:pk>/', views.tesis_modal_summary, name='tesis-modal-summary'),

    # Publicaciones
    path('publicaciones/', views.PublicacionListView.as_view(), name='publicacion'),
    path('publicacion/<int:pk>/update', views.PublicacionUpdateView.as_view(), name='publicacion-update'),
    path('publicacion/<int:pk>/delete', views.PublicacionDeleteView.as_view(), name='publicacion-delete'),
    path('publicaciones/modal/<int:pk>/', views.publicacion_modal_summary, name='publicacion-modal-summary'),

    # path('signup/', views.signup, name='signup'),
    # path('profile/update/', views.update_profile, name='profile-update'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout')
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

repos/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('americana.urls', namespace='repo-ame')),
]

admin.site.site_header = 'Universidad Americana de Acapulco'
admin.site.site_title = 'Portal de Administración'
admin.site.index_title = 'Sitio de Administración del Repositorio'

templates/banner.html
{% extends 'americana/base.html' %}
{% load static %}
{% block body %}

<nav class="navbar is-warning is-spaced">
    <div class="container">
      <div id="navMenu" class="navbar-menu">
        <div class="navbar-start">
          <a class="navbar-item">
            <p class="is-title">Campus Virtual</p>
        </a>
        </div>
        <div class="navbar-end">
          <div class="navbar-item">
            <div class="buttons">
              <a class="button is-dark">Enlace</a>
              <a class="button is-link">Botón</a>
            </div>
          </div>
        </div>
      </div>
    </div>
</nav>

<section class="hero is-large is-dark has-background">
    <img alt="Banner Acapulco" class="hero-background is-transparent" src="{% static 'img/banner_3.jpeg' %}" />
    <div class="hero-body">
      <div class="container">
        <p class="title is-spaced has-text-weight-normal has-text-justified">El Repositorio Institucional de la UAA permite integrar, publicar y consultar los contenidos académicos que genera y resguarda la Universidad</p>
        <p class="subtitle">
            <div class="field has-addons">
                <div class="control is-expanded">
                  <input class="input" type="text" placeholder="Buscar un Repositorio">
                </div>
                <div class="control">
                  <a class="button is-info">
                    Buscar
                  </a>
                </div>
            </div>
        </p>
        <p class="subtitle">
            2,797,121 recursos digitales incorporados hasta el momento
        </p>
      </div>
    </div>
</section>

<section class="hero is-link is-large">
<div class="hero-body">

</div>
</section>

{% endblock body %}

templates/filter.html
{% extends 'americana/base.html' %}
{% load static %}
{% block body %}
<section class="section">
<nav class="breadcrumb" aria-label="breadcrumbs">
    <ul>
        <li>
            <span class="icon is-small">
                <i class="fas fa-home" aria-hidden="true"></i>
            </span>
            <a href="{% url 'repo-ame:home' %}" aria-current="page">Inicio</a>
        </li>
        <li><a href="#">{{breadcrumb_key|title}}</a></li>
        <li class="is-active"><a href="#">{{breadcrumb_value|title}}</a></li>
    </ul>
</nav>
<!-- Filtros -->
<form method="get" class="box">
<div class="columns">
<div class="column">
    <div class="field is-horizontal">
        <div class="field-label is-normal">
            <label class="label">Mostrar:</label>
        </div>
        <div class="field-body">
            <div class="field">
            <div class="select is-fullwidth">
                <select name="paginate_by"
                hx-get="{% url 'repo-ame:search' %}?{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}"
                hx-target="#list-results">
                    <option>10</option>
                    <option>25</option>
                    <option>50</option>
                    <option>100</option>
                </select>
            </div>
            </div>
        </div>
    </div>
</div>
<div class="column">
    <div class="field is-horizontal">
        <div class="field-label is-normal">
            <label class="label">Tipo:</label>
        </div>
        <div class="field-body">
            <div class="field">
            <div class="select is-fullwidth">
                <select name="tipo"
                hx-get="{% url 'repo-ame:search' %}?{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}"
                hx-target="#list-results">
                    <option value="publicaciones">Publicaciones</option>
                    <option value="tesis">Tesis</option>
                    <option value="constancias">Constancias</option>
                </select>
            </div>
            </div>
        </div>
    </div>
</div>
<div class="column">
    <div class="field is-horizontal">
        <div class="field-label is-normal">
            <label class="label">Buscar:</label>
        </div>
        <div class="field-body">
            <div class="field">
            <div class="control">
                <input type="text" class="input" name="q" placeholder="Buscar por palabra clave"
                hx-get="{% url 'repo-ame:search' %}?{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}"
                hx-target="#list-results"
                hx-trigger="keyup changed delay:500ms">
            </div>
            </div>
        </div>
    </div>
</div>
</div>
</form>

<div id="list-results">
{% include 'partials/list-items.html' with obj_list=obj_list %}
</div>

</section>
{% endblock body %}

templates/index.html
{% extends 'americana/base.html' %}
{% load static %}
{% block body %}
<section class="section">
<nav class="breadcrumb" aria-label="breadcrumbs">
    <ul>
        <li class="is-active">
            <span class="icon is-small">
                <i class="fas fa-home" aria-hidden="true"></i>
            </span>
            <a href="#" aria-current="page">Inicio</a>
        </li>
        
    </ul>
</nav>
<div class="columns">
<div class="column is-9">
    <p class="title">Repositorio Digial de la Universidad Americana de Acapulco</p>
    <hr class="has-background-gray" />
    <figure class="image is-2by1">
        <img src="{% static 'img/banner_4.jpg' %}">
    </figure>
    <br/>
    <p class="subtitle is-size-3 mt-4">Añadido Recientemente</p>
    <hr class="has-background-gray" />
    <div class="list has-hoverable-list-items has-overflow-ellipsis">
    {% for publicacion in publicaciones %}
    <div class="list-item">
        <div class="list-item-image">
            <span class="icon is-large has-text-danger">
                <i class="fas fa-2x fa-file-pdf"></i>
            </span>
        </div>
        <div class="list-item-content">            
            <div class="list-item-title">
                <a href="{{publicacion.file.url}}" target="_blank">
                    {{publicacion.format_publish}}
                </a>
            </div>
            <div class="list-item-description">{{publicacion.description}}</div>
        </div>
    </div>
    {% empty %}
    <div class="list-item">
        <div class="list-item-content">
            <div class="list-item-title">
                <p class="title is-size-5">Sin Registros</p>
            </div>
        </div>
    </div>
    {% endfor %}
    </div>
</div>
<div class="column is-3">
    <div class="field has-addons">
        <div class="control is-expanded">
            <input class="input" type="text" placeholder="Encontrar repositorio">
        </div>
        <div class="control">
            <button class="button is-info">
                <span class="icon is-small">
                    <i class="fas fa-search"></i>
                </span>
            </button>
        </div>
    </div>
    <nav class="panel is-info">
        <p class="panel-heading">Programas</p>
        <a href="{% url 'repo-ame:search' %}?tipo=tesis&programa=Maestria" class="panel-block">Maestria</a>
        <a href="{% url 'repo-ame:search' %}?tipo=tesis&programa=Doctorado" class="panel-block">Doctorado</a>
    </nav>
    <nav class="panel is-info">
        <p class="panel-heading">Autor</p>
        {% for autor in autores %}
        <a href="{% url 'repo-ame:search' %}?autor={{autor.slug}}" class="panel-block">{{autor.get_full_name}}</a>
        {% empty %}
        <p class="panel-block">Sin autores registrados</p>
        {% endfor %}
    </nav>
    <nav class="panel is-info">
        <p class="panel-heading">Area</p>
        {% for area in areas %}
        <a href="{% url 'repo-ame:search' %}?area={{area.slug}}" class="panel-block">{{area.name}}</a>
        {% empty %}
        <p class="panel-block">Sin areas registradas</p>
        {% endfor %}
    </nav>
    <nav class="panel is-info">
        <p class="panel-heading">Año</p>
        {% for anio in anios %}
        <a href="{% url 'repo-ame:search' %}?anio={{anio.publish_date.year}}" class="panel-block">{{anio.publish_date.year}}</a>
        {% empty %}
        <p class="panel-block">Sin años registrados</p>
        {% endfor %}
    </nav>
</div>
</div>
</section>

{% include 'layout/gallery.html' %}

{% endblock body%}

{% block js %}
<script>
    bulmaCarousel.attach('#carousel-demo', {
        slidesToScroll: 1,
        slidesToShow: 3,
        infinite: true,
        pagination: false
    });
</script>
{% endblock js %}

templates/navbar.html
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
<div class="container">
    <a class="navbar-brand" href="#">Repo ITA</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
    <ul class="navbar-nav ml-auto">
        <li class="nav-item">
        <a class="nav-link" href="{% url 'repo-ita:home' %}">Inicio</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="articulo-menu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Articulos</a>
            <div class="dropdown-menu" aria-labelledby="articulo-menu">
            <a class="dropdown-item" href="{% url 'repo-ita:articulo-create' %}">Nuevo articulo</a>
            <a class="dropdown-item" href="{% url 'repo-ita:articulos' %}">Ver articulos</a>
            </div>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="evidencias-menu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Evidencias</a>
            <div class="dropdown-menu" aria-labelledby="evidencias-menu">
            <a class="dropdown-item" href="#">Nueva evidencia</a>
            <a class="dropdown-item" href="#">Ver evidencias</a>
            </div>
        </li>
        {% endif %}
        <li class="nav-item">
        <a class="nav-link" href="{% url 'repo-ita:search' %}">Buscar</a>
        </li>
        {% if user.is_authenticated %}
            <li class="nav-item">
            <a class="nav-link" href="{% url 'repo-ita:logout' %}">Logout</a>
            </li>
        {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'repo-ita:signup' %}" role="button">Sign Up</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'repo-ita:login' %}" role="button">Login</a>
            </li>
        {% endif %}
    </ul>
    </div>
</div>
</nav>