americana/urls.py
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.urls import path

from americana import views

app_name = 'repo-ame'

urlpatterns = [
    path('', views.index, name='home'),
    path('search', views.search, name='search'),
    path('tablero/', views.Tablero.as_view(), name='tablero'),

    # Tesis
    path('tesis/', views.TesisListView.as_view(), name='tesis'),
    path('tesis/<int:pk>/update', views.TesisUpdateView.as_view(), name='tesis-update'),
    path('tesis/<int:pk>/delete', views.TesisDeleteView.as_view(), name='tesis-delete'),
    path('tesis/modal/<int:pk>/', views.tesis_modal_summary, name='tesis-modal-summary'),

    # Publicaciones
    path('publicaciones/', views.PublicacionListView.as_view(), name='publicacion'),
    path('publicacion/<int:pk>/update', views.PublicacionUpdateView.as_view(), name='publicacion-update'),
    path('publicacion/<int:pk>/delete', views.PublicacionDeleteView.as_view(), name='publicacion-delete'),
    path('publicaciones/modal/<int:pk>/', views.publicacion_modal_summary, name='publicacion-modal-summary'),

    # path('signup/', views.signup, name='signup'),
    # path('profile/update/', views.update_profile, name='profile-update'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout')
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

repos/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('americana.urls', namespace='repo-ame')),
]

admin.site.site_header = 'Universidad Americana de Acapulco'
admin.site.site_title = 'Portal de Administración'
admin.site.index_title = 'Sitio de Administración del Repositorio'

templates/layout/footer.html
{% load static %}
<footer class="footer has-background-info has-text-white">
    <div class="columns is-centered is-vcentered">
        <div class="column is-2">
            <figure class="image">
                <img src="{% static 'img/logo_footer_hd-169x300.png' %}" style="width:90px;height:180px">
            </figure>
        </div>
        <div class="column is-3 is-offset-1">
            <p class="title is-5 has-text-white">Mapa del Sitio</p>
            <ul>
                <li>Prepa UNAM</li>
                <li>Carreras UNAM</li>
                <li>Ciencias de la Salud</li>
                <li>Maestrias</li>
                <li>Educación Livestreaming</li>
                <li>Contacto</li>
            </ul>
        </div>
        <div class="column is-3 is-offset-1">
            <p class="title is-5 has-text-white">Informes</p>
            <p>(+52) 744 487 9170</p>
            <p>Av. Universidad 1804, lote 3-B. Fraccionamiento la Bocana,</p>
            <p>C.P. 39670 Acapulco de Juárez, Gro.</p>
            <p>Siguenos en:</p>
            
                  <span class="icon is-medium">
                    <i class="fab fa-lg fa-facebook"></i>
                  </span>
                  <span class="icon is-medium">
                    <i class="fab fa-lg fa-instagram"></i>
                  </span>
              
            </div>
        </div>
    </div>
</footer>

templates/layout/gallery.html
{% load static %}
<section class="section">
    <div class="container">
        <!-- Start Carousel -->
        <div id="carousel-demo" class="carousel">
            <div class="item-1">
                <figure class="image">
                    <img src="{% static 'img/gallery/1.jpg' %}" alt="">
                </figure>
            </div>
            <div class="item-2">
                <figure class="image">
                    <img src="{% static 'img/gallery/2.jpg' %}" alt="">
                </figure>
            </div>
            <div class="item-3">
                <figure class="image">
                    <img src="{% static 'img/gallery/3.jpg' %}" alt="">
                </figure>
            </div>
            <div class="item-4">
                <figure class="image">
                    <img src="{% static 'img/gallery/4.jpg' %}" alt="">
                </figure>
            </div>
            <div class="item-5">
                <figure class="image">
                    <img src="{% static 'img/gallery/5.jpg' %}" alt="">
                </figure>
            </div>
            <div class="item-6">
                <figure class="image">
                    <img src="{% static 'img/gallery/6.jpg' %}" alt="">
                </figure>
            </div>
            <div class="item-7">
                <figure class="image">
                    <img src="{% static 'img/gallery/7.jpg' %}" alt="">
                </figure>
            </div>
            <div class="item-8">
                <figure class="image">
                    <img src="{% static 'img/gallery/8.jpg' %}" alt="">
                </figure>
            </div>
            <div class="item-9">
                <figure class="image">
                    <img src="{% static 'img/gallery/9.jpg' %}" alt="">
                </figure>
            </div>
            <div class="item-10">
                <figure class="image">
                    <img src="{% static 'img/gallery/10.jpg' %}" alt="">
                </figure>
            </div>
            <div class="item-11">
                <figure class="image">
                    <img src="{% static 'img/gallery/11.jpg' %}" alt="">
                </figure>
            </div>
            <div class="item-12">
                <figure class="image">
                    <img src="{% static 'img/gallery/12.jpg' %}" alt="">
                </figure>
            </div>
            <div class="item-13">
                <figure class="image">
                    <img src="{% static 'img/gallery/13.jpg' %}" alt="">
                </figure>
            </div>
            <div class="item-14">
                <figure class="image">
                    <img src="{% static 'img/gallery/14.jpg' %}" alt="">
                </figure>
            </div>
            <div class="item-15">
                <figure class="image">
                    <img src="{% static 'img/gallery/15.jpg' %}" alt="">
                </figure>
            </div>
            <div class="item-16">
                <figure class="image">
                    <img src="{% static 'img/gallery/16.jpg' %}" alt="">
                </figure>
            </div>
            <div class="item-17">
                <figure class="image">
                    <img src="{% static 'img/gallery/17.jpg' %}" alt="">
                </figure>
            </div>
            <div class="item-18">
                <figure class="image">
                    <img src="{% static 'img/gallery/18.jpg' %}" alt="">
                </figure>
            </div>
            <div class="item-19">
                <figure class="image">
                    <img src="{% static 'img/gallery/19.jpg' %}" alt="">
                </figure>
            </div>
            <div class="item-20">
                <figure class="image">
                    <img src="{% static 'img/gallery/20.jpg' %}" alt="">
                </figure>
            </div>
        </div>
        <!-- End Carousel -->
    </div>
</section>

templates/layout/navbar.html
{% load static %}
{% comment %}
<nav class="navbar is-light is-spaced has-shadow" role="navigation" aria-label="main navigation">
<div class="container">
<div class="navbar-brand">
  <a class="navbar-item" href="{% url 'repo-ame:home' %}">
    <img src="{% static 'img/logoUAAMedium.png' %}" width="280" height="90" alt="Universidad Americana de Acapulco">
  </a>
  <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbar-ame">
    <span aria-hidden="true"></span>
    <span aria-hidden="true"></span>
    <span aria-hidden="true"></span>
  </a>
</div>
<div id="navbar-ame" class="navbar-menu">
  <div class="navbar-start">
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">Menú</a>
        <div class="navbar-dropdown is-boxed">
          {% if user.is_authenticated %}
          <a class="navbar-item" href="{% url 'repo-ame:tablero' %}">Tablero</a>
          {% endif %}
          <a class="navbar-item" href="{% url 'repo-ame:tesis' %}">Tesis</a>
          <a class="navbar-item" href="{% url 'repo-ame:publicacion' %}">Publicaciones</a>
        </div>
      </div>
  </div>
  
  <div class="navbar-end">
    {% if user.is_authenticated  %}
    <div class="navbar-item has-dropdown is-hoverable">
      <a class="navbar-link">{{user.username|capfirst}}</a>
      <div class="navbar-dropdown">
        <a class="navbar-item" href="{% url 'admin:index' %}">Ir al sitio de administración</a>
        <hr class="navbar-divider">
        <a class="navbar-item" href="{% url 'repo-ame:logout' %}">Cerrar sesión</a>
      </div>
    </div>
    {% else %}
    <div class="navbar-item">
    <div class="buttons">
        <a class="button is-outlined" href="{% url 'repo-ame:login' %}">Iniciar Sesión</a>
    </div>
    </div>
    {% endif %}
  </div>
</div>
</div>
</nav>
{% endcomment %}
<section class="section has-background-light">
  <nav class="level">
    <div class="level-left">
        <p class="level-item has-text-centered">
        <a href="{% url 'repo-ame:home' %}">
          <img src="{% static 'img/logoUAAMedium.png' %}" style="height: 60px;" alt="Universidad Americana de Acapulco">
        </a>
        </p>
    </div>
    <div class="level-right">
    <p class="level-item">
        <a class="button is-info is-outlined" href="{% url 'repo-ame:login' %}">Iniciar Sesión</a>
    </p>
    </div>
  </nav>
</section>